### ISSUE TITLE
Add semantic release to trigger builds

### ISSUE THREAD

**Issue by jeremierobert-coveo** [coveo/search-ui-extensions#15]
https://github.com/semantic-release/semantic-release This should be a good way to avoid unecessary scripts.

What do you think ? @louis-bompart @mikegron

**Comment by louis-bompart** [comment]
How much do you want to commit (🥁) to semantics there?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by jeremierobert-coveo** [comment]
I like the use of commit message convention

**Comment by louis-bompart** [comment]
I do to, however one thing to be aware of is that if you want to lint them, semantic-release will trip on all the commit that doesn't fit (so all commits so far)

**Comment by jeremierobert-coveo** [comment]
ark

**Comment by jeremierobert-coveo** [comment]
Then I prefer not to add it

**Comment by louis-bompart** [comment]
Try a dry run tho, if it passes as expected then I was wrong
